[tool.poetry]
name = "JGLUE-evaluation-scripts"
version = "0.1.0"
description = ""
authors = ["nobu-g <ueda-n127@hotmail.co.jp>"]
maintainers = ["nobu-g <ueda-n127@hotmail.co.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
torch = "~2.0.0,!=2.0.1"  # https://github.com/pytorch/pytorch/issues/100974
transformers = { version = "~4.33.3", extras = ["sentencepiece"] }
tokenizers = "^0.13.2"
lightning = "~2.1.0"
torchmetrics = "^1.1"
omegaconf = "^2.3"
hydra-core = "^1.3"
rich = "^13.3"
datasets = "^2.10"
rhoknp = "^1.4"
jaconv = "^0.3.4"
mecab-python3 = "^1.0"

[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.9"
types-attrs = "^19.1"
wandb = "^0.15.0"
tabulate = "^0.9.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4"

[tool.black]
line-length = 120
target-version = ["py39", "py310", "py311"]

[tool.isort]
line_length = 120
py_version = 39
profile = "black"
src_paths = ["src"]

[tool.flake8]
# E203 is not PEP8 compliant and black insert space around slice (https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated)
# E501: Line too long. Disable it to allow long lines of comments and print lines which black allows.
# W503: line break before binary operator (https://www.flake8rules.com/rules/W503.html)
ignore = ["E203", "E501", "W503"]
max-line-length = 120

[tool.mypy]
python_version = 3.9

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore::UserWarning',
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
