model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${run_dir}
  filename: "{epoch}-{step}"
  auto_insert_metric_name: false
  monitor: ${monitor}
  mode: ${mode}
  save_top_k: 1
  every_n_epochs: 1
  save_weights_only: true
