max_seq_length: ${max_seq_length}
split: train
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${encoder.pretrained_model_name_or_path}
  _convert_: all
