_target_: pytorch_lightning.Trainer
gradient_clip_val: 0.5
accumulate_grad_batches: null
max_epochs: ${max_epochs}
min_epochs: 1
accelerator: "auto"     # set gpu or cpu automatically
strategy: ddp
precision: 32
