model_name_or_path: ku-nlp/deberta-v2-tiny-japanese
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${..model_name_or_path}
  _convert_: all
segmenter_kwargs:
  analyzer: jumanpp
  h2z: false
