model_name_or_path: studio-ousia/luke-japanese-large-lite
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${..model_name_or_path}
  _convert_: all
segmenter_kwargs:
  analyzer: null
  h2z: false
