max_seq_length: ${max_seq_length}
split: validation
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${model_name_or_path}
  _convert_: all
limit_examples: ${limit_examples}
