defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, progress_bar, lr_monitor]
  - datamodule: jcqa
  - logger: wandb
  - module: jcqa
  - optimizer: adamw
  - scheduler: cosine_schedule_with_warmup
  - trainer: default
  - _self_

model_name_or_path: ku-nlp/deberta-v2-large-japanese
max_seq_length: 64
checkpoint_path: ""
limit_examples: -1

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/accuracy
mode: max

# hyper-parameters to be tuned
lr: 3e-5
max_epochs: 6
warmup_steps: 500
effective_batch_size: 64

# environment dependent settings
devices: ${oc.env:DEVICES,0}
max_batches_per_device: ${oc.env:MAX_BATCHES_PER_DEVICE,2}
num_workers: ${oc.env:NUM_WORKERS,4}
