defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, progress_bar, lr_monitor]
  - datamodule: jsquad
  - logger: wandb
  - model: deberta_v2_large
  - module: jsquad
  - optimizer: adamw
  - scheduler: cosine_schedule_with_warmup
  - trainer: default
  - _self_

max_seq_length: 384
checkpoint_path: ""
limit_examples: -1

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/f1
mode: max

# hyper-parameters to be tuned
lr: 5e-5
max_epochs: 4
warmup_steps: null
warmup_ratio: 0.1
effective_batch_size: 32
