_target_: lightning.pytorch.loggers.WandbLogger
name: ${name}-${hydra:job.num}
save_dir: ${work_dir}
project: ${project}
group: ${name}
tags:
  - ${config_name}
settings:
  _target_: wandb.Settings
  start_method: fork
