name: Test

on: [ push, pull_request ]

jobs:
  test:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --without dev
      - name: Run tests
        run: |
          poetry run pytest --cov=./ --cov-report=xml
        env:
          XDG_CACHE_HOME: ${{ github.workspace }}/.cache
